### ISSUE TITLE
Integrate changes in branches cas741 and erpa

### ISSUE THREAD

**Issue by gabrielasd** [gabrielasd/pyeom#59]
## Description
The code in the branch [__cas741__](https://github.com/gabrielasd/eomee/tree/cas741) supports
evaluating the excited states wavefunctions and energies solution to the EOM equations but doesn't include the energy corrections through eRPA which is being added in a separate branch. 
Both branches chare the commit 4d38806efd54364fb8ba1d5931c4024357496f41 but their current package structure significantly differ (__cas741__ follows the software development patterns from the course CAS 741 [ref.](https://www.taylorfrancis.com/chapters/edit/10.1201/9781315368924-12/rational-document-driven-design-process-scientific-software-spencer-smith)
In moving forward some of the strategies used in __cas741__, will be relaxed and [Sphinx](https://www.sphinx-doc.org/en/master/) will be used for generating the documentation instead of maintaining pdf files (see issue #58)

## Tasks
- [x] Rename folder docs/ to docs_cas741/ and move refs/ inside it
- [x] Move content inside eomee/eomes/eom to parent directory and erase eom/. Fix modules imports.
- [x] Move tests folder from eomee/ to emoee/eomes/. Fix modules imports.
- [x] Merge cas741 and erpa branches.
